### ISSUE TITLE
gráfico para Usuario no existe

### ISSUE THREAD

**Issue by ferjflores** [ferjflores/segana#12]

**Comment by carmeladf** [comment]
me vas a matar. pero la casilla de usuario impactado debería estar asociado a el tema, matriz y actor, perdomame; aun ni siquiera se como demonios voy a analizar algo como eso. De verdad perdona. pero hay noticias que son solo enunciaciones pero son necesarias contarlas

**Comment by carmeladf** [comment]
el problema del usuario es que a 1- es participante y por tanto sale como actor, 2.- es simplemente enunciado (como cuando lo denuncias y ya) o cuando dicen que participo en tal actividad 
la enunciación es la que me dificulta para caracterizarlo pero si no lo asocio con el tema- matriz- actor me contabiliza toda la nota completa  me da un gran margen de error
